name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build darkc (Linux)
        run: ./darkc examples/darkc.dark -o darkc --target linux
      - name: Build darkc.exe (Windows)
        run: ./darkc examples/darkc.dark -o darkc.exe --target windows
      - name: Test wconn2
        run: ./darkc examples/libtest_wconn2.dark -o wconn2.exe --target windows
      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            darkc
            darkc.exe
            wconn2.exe